version: 2.1

orbs:
  node: circleci/node@4.0.0
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default
    
    steps:
      - checkout
      - run:
          name: "Install Chrome"
          shell: powershell.exe
          command: |
            $LocalTempDir = $env:TEMP; $ChromeInstaller = "ChromeInstaller.exe"; (new-object System.Net.WebClient).DownloadFile('http://dl.google.com/chrome/install/375.126/chrome_installer.exe', "$LocalTempDir\$ChromeInstaller"); & "$LocalTempDir\$ChromeInstaller" /silent /install; $Process2Monitor = "ChromeInstaller"; Do { $ProcessesFound = Get-Process | ?{$Process2Monitor -contains $_.Name} | Select-Object -ExpandProperty Name; If ($ProcessesFound) { "Still running: $($ProcessesFound -join ', ')" | Write-Host; Start-Sleep -Seconds 2 } else { rm "$LocalTempDir\$ChromeInstaller" -ErrorAction SilentlyContinue -Verbose } } Until (!$ProcessesFound)

      #- node/install:
      #    install-yarn: true 
      #    lts: true
      #- run: npm --versions
      #- run: yarn --version
      - run: npm run test:chrome -- --licenseToken 9338F7CF223C0DD1D72E7A074425D017A2964CD20444F8227C23571CC674947C