version: 2.1

orbs:
  node: circleci/node@4.0.0
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      #- node/install:
      #    install-yarn: true
      #    lts: true
      #- run: npm --versions
      #- run: yarn --version
      #- run: .circleci/build.sh
      - run: ./node_modules/.bin/gondola -c gondola.chrome.json run --steps --licenseToken='9338F7CF223C0DD1D72E7A074425D017A2964CD20444F8227C23571CC674947C' --reporter mochawesome