version: 2.1

orbs:
  node: circleci/node@4.0.0
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      #- node/install:
      #    install-yarn: true
      #    lts: true
      #- run: npm --versions
      #- run: yarn --version
      #- run: .circleci/build.sh
      - run: npm run test:chrome