version: 2.1

orbs:
  node: circleci/node@4.0.0

jobs:
  build:
    machine:
      image: windows-server-2019-nvidia:stable
    parameters:
      browser:
        type: string
        default: chrome
    steps:
      - checkout
      #- node/install:
      #    install-yarn: true
      #    lts: true
      #- run: npm --versions
      #- run: yarn --version
      #- run: .circleci/build.sh
      - run: ./node_modules/.bin/gondola -c gondola.chrome.json run --steps --reporter mochawesome