version: 2.1

orbs:
  node: circleci/node@4.0.0

jobs:
  build:
    machine:
      image: 'circleci/classic:latest'
    parameters:
      browser:
        type: string
        default: chrome
    steps:
      - checkout
      #- node/install:
      #    install-yarn: true
      #    lts: true
      #- run: npm --versions
      #- run: yarn --version
      #- run: .circleci/build.sh
      - run: npm test